dist: trusty
#sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
#  - sudo apt-get install -qq libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
#  - wget http://archive.apache.org/dist/thrift/0.9.1/thrift-0.9.1.tar.gz
#  - tar xfz thrift-0.9.1.tar.gz
#  - cd thrift-0.9.1
#  - chmod +x ./configure
#  - ./configure --disable-gen-erl --disable-gen-hs --without-cpp --without-boost --without-qt4 --without-c_glib --without-csharp --without-erlang --without-python --without-perl --without-php --without-php_extension --without-ruby --without-haskell --without-go --without-d
#  - sudo make install
#  - cd ..
  - pip install --user codecov
  - git clone https://github.com/thulab/tsfile.git
  - cd tsfile 
#  - git checkout hxd_tsfile_sdk
  - mvn install -DskipTests=true
  - cd ..

script: 
# only SNAPSHOT version needs to do the following phase
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash) -t 853796a6-a626-422f-a897-ac233e121f8f
  - mvn clean test
  
after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash) -t 853796a6-a626-422f-a897-ac233e121f8f
