dist: trusty
#sudo: required

language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

before_install:

script: 
  - mvn clean test -pl iotdb -am -Dtsfile.test.skip=true -Djdbc.test.skip=true -Dit.test.includes="**/IoTDB*Test.java"

after_success:

