coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: no
    changes: no

ignore:
#  - "*/interface/thrift/**/*.java"  # ignore thrift-gen folders and all its contents
  - "**/generated-classes/**/*.java"
  - "**/generated-sources/**/*.java"
  - "grafana/**/*.java"
  - "spark/**/*.java"
  - "hadoop/**/*.java"
  - "**/pom.xml"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.cmd"
  - "**/*.bat"
  - "**/*.yml"
  - ".mvn"
  - "mvnw"
  - "NOTICE"
  - "NOTICE-binary"
  - "License"
  - "LICENSE-binary"
