package cn.edu.tsinghua.iotdb.auth.entity;

/**
 * This enum class contains all available privileges in IoTDB.
 */
public enum PrivilegeType {
    CREATE, INSERT, UPDATE, READ, DELETE,
    CREATE_USER, DELETE_USER, MODIFY_PASSWORD, LIST_USER, GRANT_USER_PRIVILEGE, REVOKE_USER_PRIVILEGE, GRANT_USER_ROLE, REVOKE_USER_ROLE,
    CREATE_ROLE, DELETE_ROLE, LIST_ROLE, GRANT_ROLE_PRIVILEGE, REVOKE_ROLE_PRIVILEGE
}
