/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.thu.tsfiledb.service.rpc.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-7-27")
public class TSFileNodeNameAllResp implements org.apache.thrift.TBase<TSFileNodeNameAllResp, TSFileNodeNameAllResp._Fields>, java.io.Serializable, Cloneable, Comparable<TSFileNodeNameAllResp> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSFileNodeNameAllResp");

  private static final org.apache.thrift.protocol.TField FILE_NODES_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("fileNodesList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TSFileNodeNameAllRespStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TSFileNodeNameAllRespTupleSchemeFactory());
  }

  public List<String> fileNodesList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILE_NODES_LIST((short)1, "fileNodesList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_NODES_LIST
          return FILE_NODES_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_NODES_LIST, new org.apache.thrift.meta_data.FieldMetaData("fileNodesList", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSFileNodeNameAllResp.class, metaDataMap);
  }

  public TSFileNodeNameAllResp() {
  }

  public TSFileNodeNameAllResp(
    List<String> fileNodesList)
  {
    this();
    this.fileNodesList = fileNodesList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSFileNodeNameAllResp(TSFileNodeNameAllResp other) {
    if (other.isSetFileNodesList()) {
      List<String> __this__fileNodesList = new ArrayList<String>(other.fileNodesList);
      this.fileNodesList = __this__fileNodesList;
    }
  }

  public TSFileNodeNameAllResp deepCopy() {
    return new TSFileNodeNameAllResp(this);
  }

  @Override
  public void clear() {
    this.fileNodesList = null;
  }

  public int getFileNodesListSize() {
    return (this.fileNodesList == null) ? 0 : this.fileNodesList.size();
  }

  public java.util.Iterator<String> getFileNodesListIterator() {
    return (this.fileNodesList == null) ? null : this.fileNodesList.iterator();
  }

  public void addToFileNodesList(String elem) {
    if (this.fileNodesList == null) {
      this.fileNodesList = new ArrayList<String>();
    }
    this.fileNodesList.add(elem);
  }

  public List<String> getFileNodesList() {
    return this.fileNodesList;
  }

  public TSFileNodeNameAllResp setFileNodesList(List<String> fileNodesList) {
    this.fileNodesList = fileNodesList;
    return this;
  }

  public void unsetFileNodesList() {
    this.fileNodesList = null;
  }

  /** Returns true if field fileNodesList is set (has been assigned a value) and false otherwise */
  public boolean isSetFileNodesList() {
    return this.fileNodesList != null;
  }

  public void setFileNodesListIsSet(boolean value) {
    if (!value) {
      this.fileNodesList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_NODES_LIST:
      if (value == null) {
        unsetFileNodesList();
      } else {
        setFileNodesList((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_NODES_LIST:
      return getFileNodesList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_NODES_LIST:
      return isSetFileNodesList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TSFileNodeNameAllResp)
      return this.equals((TSFileNodeNameAllResp)that);
    return false;
  }

  public boolean equals(TSFileNodeNameAllResp that) {
    if (that == null)
      return false;

    boolean this_present_fileNodesList = true && this.isSetFileNodesList();
    boolean that_present_fileNodesList = true && that.isSetFileNodesList();
    if (this_present_fileNodesList || that_present_fileNodesList) {
      if (!(this_present_fileNodesList && that_present_fileNodesList))
        return false;
      if (!this.fileNodesList.equals(that.fileNodesList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_fileNodesList = true && (isSetFileNodesList());
    list.add(present_fileNodesList);
    if (present_fileNodesList)
      list.add(fileNodesList);

    return list.hashCode();
  }

  @Override
  public int compareTo(TSFileNodeNameAllResp other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileNodesList()).compareTo(other.isSetFileNodesList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileNodesList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileNodesList, other.fileNodesList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TSFileNodeNameAllResp(");
    boolean first = true;

    sb.append("fileNodesList:");
    if (this.fileNodesList == null) {
      sb.append("null");
    } else {
      sb.append(this.fileNodesList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (fileNodesList == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'fileNodesList' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSFileNodeNameAllRespStandardSchemeFactory implements SchemeFactory {
    public TSFileNodeNameAllRespStandardScheme getScheme() {
      return new TSFileNodeNameAllRespStandardScheme();
    }
  }

  private static class TSFileNodeNameAllRespStandardScheme extends StandardScheme<TSFileNodeNameAllResp> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSFileNodeNameAllResp struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_NODES_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list160 = iprot.readListBegin();
                struct.fileNodesList = new ArrayList<String>(_list160.size);
                String _elem161;
                for (int _i162 = 0; _i162 < _list160.size; ++_i162)
                {
                  _elem161 = iprot.readString();
                  struct.fileNodesList.add(_elem161);
                }
                iprot.readListEnd();
              }
              struct.setFileNodesListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSFileNodeNameAllResp struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fileNodesList != null) {
        oprot.writeFieldBegin(FILE_NODES_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.fileNodesList.size()));
          for (String _iter163 : struct.fileNodesList)
          {
            oprot.writeString(_iter163);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSFileNodeNameAllRespTupleSchemeFactory implements SchemeFactory {
    public TSFileNodeNameAllRespTupleScheme getScheme() {
      return new TSFileNodeNameAllRespTupleScheme();
    }
  }

  private static class TSFileNodeNameAllRespTupleScheme extends TupleScheme<TSFileNodeNameAllResp> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSFileNodeNameAllResp struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.fileNodesList.size());
        for (String _iter164 : struct.fileNodesList)
        {
          oprot.writeString(_iter164);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSFileNodeNameAllResp struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list165 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.fileNodesList = new ArrayList<String>(_list165.size);
        String _elem166;
        for (int _i167 = 0; _i167 < _list165.size; ++_i167)
        {
          _elem166 = iprot.readString();
          struct.fileNodesList.add(_elem166);
        }
      }
      struct.setFileNodesListIsSet(true);
    }
  }

}

