# JDBC Server configuration

# port which JDBC server listens to
rpc_port=6667

# Write ahead log configuration

# is write ahead log enable
enable_wal=true

# When the total number of write ahead log in the file and memory reaches the specified size, all the logs are compressed and the unused logs are removed
# Increase this value, it will lead to short write pause. Decrease this value, it will increase IO and CPU consumption
wal_cleanup_threshold=500000

# When a certain amount ofwrite ahead log is reached, it will be flushed to disk
# It is possible to lose at most flush_wal_threshold operations
flush_wal_threshold=10000

# The cycle when write ahead log is periodically refreshed to disk(in milliseconds)
# It is possible to lose at most flush_wal_period_in_ms ms operations
flush_wal_period_in_ms=10

# database features configuration

# data dir
# If this value starts with "/", use absolute path. Otherwise, it will save the data in the relative path directory under the IoTDB folder
# For windows platform
# data_dir=D:\\iotdb\\data
# For Linux platform
# data_dir=/path/iotdb/data

# The maximum concurrent thread number for merging overflow
# Increase this value, it will increase IO and CPU consumption
# Decrease this value, when there is much overflow data, it will increase disk usage, which will reduce read speed
merge_concurrent_threads=10

# Maximum number of folders open at the same time
# Increase this value, it will use more memory, random I/O becomes smaller, file fragmentation (i.e., group) is more neat.
# Decrease this value, it will use less memory, random I/O becomes greater, file fragmentation is less neat.
# group_size_in_byte * max_opened_folder = theoretical value of maximum memory occupancy
# For an application, the total amount of folder is equal to the number of storage_group settings in SQL
max_opened_folder=100

# The amount of data that is read every time when IoTDB merge data.
fetch_size=10000

# The period time of flushing data from memory to file. 
# The unit is second.
period_time_for_flush_in_second=3600
# The period time for merge overflow data with tsfile data.
# The unit is second.
period_time_for_merge_in_second=7200


# time zone of server side
# default value is +08:00
# eg. +08:00, -01:00
time_zone=+08:00

# if memory used by write reaches this threshold, auto flush will be triggered, in byte, 8GB by default
mem_threshold_warning=23622320128

# if memory used by write reaches this threshold, write will be blocked, in byte, 16GB by default
mem_threshold_dangerous=25769803776

# every such interval, a thread will check if memory exceeds mem_threshold_warning
# if do exceed, auto flush will be triggered, in ms, 1s by default
mem_monitor_interval=1000

# Decide how to control memory used by inserting data.
# 0 is RecordMemController, which count the size of every record (tuple).
# 1 is JVMMemController, which use JVM heap memory as threshold.
mem_controller_type=1

# Statistics Monitor configuration
# default monitor is enabled, and write statistics info to IoTDB every 5 seconds
# Choose to change the back_loop_period >= 1 seconds
enable_stat_monitor = true
back_loop_period = 5